language: dart
dart:
- stable
- dev
before_script:
- cd ..
- wget https://github.com/jathak/scheme_impl_skeleton/archive/master.zip
- unzip master.zip
- cd scheme_impl_skeleton-master
- wget -O lib/impl.dart $PRIVATE_IMPL
- pub get
- cd $TRAVIS_BUILD_DIR
script:
- pub run grinder check
- dartfmt -n --set-exit-if-changed .
- dartanalyzer --fatal-warnings .
- dart ../scheme_impl_skeleton-master/test/scm.dart