name: cs61a_scheme
description: Dart implementation of 61A Scheme.
version: 2.0.0-beta
homepage: https://scheme.cs61a.org
author: Jen Thakar <jthakar@berkeley.edu>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  analyzer: ^0.30.0+2
  dart2_constant: ^1.0.1
  quiver_hashcode: ^1.0.0
  rational: ^0.1.11

dev_dependencies:
  # Implementation library
  cs61a_scheme_impl:
    path: ../dart_scheme_impl

  # Core library tools
  dart_style: ^1.0.7
  dependency_validator: ^1.1.1
  grinder: ^0.8.0+3
  test: ^0.12.0

  # CLI REPL
  cli_repl: ^0.0.1

  # Web app building
  dart_to_js_script_rewriter: ^1.0.3
  transform_sass: ^0.3.1

transformers:
  - transform_sass
  - dart_to_js_script_rewriter
